### ISSUE TITLE
gpredict values don't match pypredict for live observation

### ISSUE THREAD

**Issue by rosh93** [nsat/pypredict#20]
The azimuth and elevation returned by `pypredict.observe` don't seem to be the same as those outputted by gpredict in the live view. The pypredict `orbit` number is also one more than gpredict. The latitude and longitude values do seem to match up.

I've checked a few different ground station/satellite combos and made sure the TLEs match; they all return the +1 orbit difference as well as different az/el numbers.

Below is a screenshot of a predict.observe output between SFGS and Lemur 1 and the gpredict screen at the same time:

![image](https://cloud.githubusercontent.com/assets/3818834/6033802/4c4ba692-abcf-11e4-8672-d5c6fe5c8d3e.png)

Is this a bug or am I using `pypredict.observe` incorrectly? Thanks!

**Comment by jtrutna** [comment]
Oooh, a bug!  I'll check it out.  Do you have the QTH and TLE database files you're using?

**Comment by rosh93** [comment]
The TLE was `tle = predict.tle(40044)` and the qth was the SFGS lat/lon/altitude `('37.7727', '-122.4070', 25)`
On gpredict it was the same thing, the TLE was pulled from our tle service `http://tle.nanosatisfi.com/40044` and the ground station was put in with those lat/lon/alt values.

**Comment by rosh93** [comment]
Turns out I was using `East` Longitude! Pypredict takes `West` Longitude values for QTH. Thanks for the info on that.
